"""bootstrap postgres and vector

Revision ID: 20a0a78348e8
Revises:
Create Date: 2026-09-11 20:11:05.990129

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20a0a78348e8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_results",
        sa.Column("workflow_id", sa.String(length=200), nullable=False),
        sa.Column("step_id", sa.String(length=100), nullable=False),
        sa.Column("input_hash", sa.String(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("workflow_id", "step_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("auth_subject", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_subject"),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ideas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("pitch", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(visibility = 'workspace' AND workspace_id IS NOT NULL) "
            "OR (visibility = 'public' AND workspace_id IS NULL)"
        ),
        sa.CheckConstraint("lang IN ('fr', 'en')"),
        sa.CheckConstraint("stage IN ('seed', 'iterating', 'team_formed')"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        sa.UniqueConstraint("source", "source_id"),
    )
    op.create_index(op.f("ix_ideas_workspace_id"), "ideas", ["workspace_id"], unique=False)
    op.create_table(
        "workspace_memberships",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.CheckConstraint("role IN ('admin', 'member')"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
    )
    op.create_table(
        "idea_embeddings",
        sa.Column("idea_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("lang IN ('fr', 'en')"),
        sa.CheckConstraint("model = 'text-embedding-3-large'"),
        sa.ForeignKeyConstraint(
            ["idea_id"],
            ["ideas.id"],
        ),
        sa.PrimaryKeyConstraint("idea_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("idea_embeddings")
    op.drop_table("workspace_memberships")
    op.drop_index(op.f("ix_ideas_workspace_id"), table_name="ideas")
    op.drop_table("ideas")
    op.drop_table("workspaces")
    op.drop_table("users")
    op.drop_table("agent_results")
    # ### end Alembic commands ###
